#!/usr/bin/env python3
"""Generate docs/skills.md - the skill catalog - from the skills' own frontmatter.

The catalog cannot rot because it is derived, never hand-written: for every
`skills/*/SKILL.md`, take the frontmatter description (trigger-first per the CSO rule) and
group the skills by their taxonomy category prefix (`skill-taxonomy.json`). A future skill
appears in the catalog by construction at its release's regeneration.

    build_skill_docs.py [--skills-dir DIR] [--taxonomy FILE] [--out FILE] [--check]

`--check` verifies the committed catalog is in sync (exit 1 if stale) - wired into the
hooks pytest suite. Exit 2 when it could not run: the taxonomy is missing or unusable, the
--skills-dir does not exist, the catalog cannot be written, or (--check) there is no readable
catalog to compare. Pure standard library; ASCII.
"""
import argparse
import json
import sys
from pathlib import Path

from skill_frontmatter import description as _description

_HEADER = """\
<!-- GENERATED by plugins/bitranox/hooks/build_skill_docs.py - do not edit by hand.
     Regenerate: python3 plugins/bitranox/hooks/build_skill_docs.py -->

# Skill catalog

All %d skills shipped by the `bitranox` plugin, grouped by taxonomy category
([`skill-taxonomy.json`](../plugins/bitranox/skill-taxonomy.json)). Invoke any of them as
`/bitranox:<skill>`; Claude also picks one up automatically when a task matches its
description. Each description below is the skill's own trigger description - it states WHEN
the skill fires.
"""


class Unusable(Exception):
    """An input the catalog cannot be built from (exit 2, not a stale-catalog finding)."""


def load_categories(taxonomy_file):
    """The taxonomy's `categories` mapping, or `Unusable` naming why it cannot be read."""
    try:
        data = json.loads(Path(taxonomy_file).read_text(encoding="utf-8"))
    except (OSError, ValueError) as exc:  # ValueError covers bad JSON and undecodable bytes
        raise Unusable("cannot read the taxonomy %s: %s" % (taxonomy_file, exc)) from exc
    categories = data.get("categories") if isinstance(data, dict) else None
    if not isinstance(categories, dict):
        raise Unusable("the taxonomy %s has no 'categories' object" % taxonomy_file)
    return categories


def render(skills_dir, taxonomy_file):
    """The full catalog markdown for the given skills dir and taxonomy file."""
    if not Path(skills_dir).is_dir():
        # Globbing a missing dir finds nothing, and the result was an "All 0 skills" catalog.
        raise Unusable("--skills-dir is not a directory: %s" % skills_dir)
    categories = load_categories(taxonomy_file)
    grouped = {}
    total = 0
    for skill_md in sorted(Path(skills_dir).glob("*/SKILL.md")):
        name = skill_md.parent.name
        prefix = name.split("-", 1)[0]
        key = prefix if prefix in categories else "uncategorized"
        grouped.setdefault(key, []).append((name, _description(skill_md)))
        total += 1
    lines = [_HEADER % total]
    order = [c for c in categories if c in grouped] + (
        ["uncategorized"] if "uncategorized" in grouped else [])
    for cat in order:
        desc = categories.get(cat, {}).get("desc", "Skills outside the taxonomy prefixes")
        lines.append("\n## %s\n\n%s.\n" % (cat, desc.rstrip(".")))
        for name, skill_desc in grouped[cat]:
            lines.append("- [`%s`](../plugins/bitranox/skills/%s/SKILL.md) - %s"
                         % (name, name, skill_desc))
    return "\n".join(lines) + "\n"


def main(argv=None):
    here = Path(__file__).resolve().parent
    ap = argparse.ArgumentParser(description="Generate docs/skills.md from skill descriptions.")
    ap.add_argument("--skills-dir", default=str(here.parent / "skills"))
    ap.add_argument("--taxonomy", default=str(here.parent / "skill-taxonomy.json"))
    ap.add_argument("--out", default=str(here.parents[2] / "docs" / "skills.md"))
    ap.add_argument("--check", action="store_true", help="verify the committed catalog is in sync")
    args = ap.parse_args(argv if argv is not None else sys.argv[1:])
    try:
        text = render(args.skills_dir, args.taxonomy)
    except Unusable as exc:
        print("build_skill_docs: %s" % exc, file=sys.stderr)
        return 2
    out = Path(args.out)
    if args.check:
        try:
            current = out.read_text(encoding="utf-8")
        except OSError:
            # Not "stale": outside the source repo the default --out points at a docs/ that never
            # ships, and "run build_skill_docs.py" would only write a catalog nobody reads there.
            # Nothing to compare is could-not-run (2), not the stale finding (1).
            print("docs/skills.md is missing: %s" % out, file=sys.stderr)
            return 2
        except ValueError as exc:
            print("docs/skills.md is not readable UTF-8: %s (%s)" % (out, exc), file=sys.stderr)
            return 2
        if current == text:
            print("docs/skills.md in sync")
            return 0
        print("docs/skills.md is STALE - run build_skill_docs.py", file=sys.stderr)
        return 1
    try:
        out.write_text(text, encoding="utf-8", newline="\n")
    except OSError as exc:
        print("build_skill_docs: cannot write %s: %s" % (out, exc), file=sys.stderr)
        return 2
    print("wrote %s" % out)
    return 0


if __name__ == "__main__":
    sys.exit(main())
