#!/usr/bin/env python3
"""Generate docs/skills.md - the skill catalog - from the skills' own frontmatter.

The catalog cannot rot because it is derived, never hand-written: for every
`skills/*/SKILL.md`, take the frontmatter description (trigger-first per the CSO rule) and
group the skills by their taxonomy category prefix (`skill-taxonomy.json`). A future skill
appears in the catalog by construction at its release's regeneration.

    build_skill_docs.py [--skills-dir DIR] [--taxonomy FILE] [--out FILE] [--check]

`--check` verifies the committed catalog is in sync (exit 1 if stale) - wired into the
hooks pytest suite. Pure standard library; ASCII.
"""
import argparse
import json
import sys
from pathlib import Path

from build_skill_triggers import _description

_HEADER = """\
<!-- GENERATED by plugins/bitranox/hooks/build_skill_docs.py - do not edit by hand.
     Regenerate: python3 plugins/bitranox/hooks/build_skill_docs.py -->

# Skill catalog

All %d skills shipped by the `bitranox` plugin, grouped by taxonomy category
([`skill-taxonomy.json`](../plugins/bitranox/skill-taxonomy.json)). Invoke any of them as
`/bitranox:<skill>`; Claude also picks one up automatically when a task matches its
description. Each description below is the skill's own trigger description - it states WHEN
the skill fires.
"""


def _clean(desc):
    """Strip frontmatter authoring artifacts (a leading '>', wrapping quotes) for display."""
    desc = (desc or "").strip().lstrip(">").strip()
    if len(desc) > 1 and desc[0] == desc[-1] == '"':
        desc = desc[1:-1].strip()
    return desc


def render(skills_dir, taxonomy_file):
    """The full catalog markdown for the given skills dir and taxonomy file."""
    categories = json.loads(Path(taxonomy_file).read_text(encoding="utf-8"))["categories"]
    grouped = {}
    total = 0
    for skill_md in sorted(Path(skills_dir).glob("*/SKILL.md")):
        name = skill_md.parent.name
        prefix = name.split("-", 1)[0]
        key = prefix if prefix in categories else "uncategorized"
        grouped.setdefault(key, []).append((name, _clean(_description(skill_md))))
        total += 1
    lines = [_HEADER % total]
    order = [c for c in categories if c in grouped] + (
        ["uncategorized"] if "uncategorized" in grouped else [])
    for cat in order:
        desc = categories.get(cat, {}).get("desc", "Skills outside the taxonomy prefixes")
        lines.append("\n## %s\n\n%s.\n" % (cat, desc.rstrip(".")))
        for name, skill_desc in grouped[cat]:
            lines.append("- [`%s`](../plugins/bitranox/skills/%s/SKILL.md) - %s"
                         % (name, name, skill_desc))
    return "\n".join(lines) + "\n"


def main(argv=None):
    here = Path(__file__).resolve().parent
    ap = argparse.ArgumentParser(description="Generate docs/skills.md from skill descriptions.")
    ap.add_argument("--skills-dir", default=str(here.parent / "skills"))
    ap.add_argument("--taxonomy", default=str(here.parent / "skill-taxonomy.json"))
    ap.add_argument("--out", default=str(here.parents[2] / "docs" / "skills.md"))
    ap.add_argument("--check", action="store_true", help="verify the committed catalog is in sync")
    args = ap.parse_args(argv if argv is not None else sys.argv[1:])
    text = render(args.skills_dir, args.taxonomy)
    out = Path(args.out)
    if args.check:
        try:
            if out.read_text(encoding="utf-8") == text:
                print("docs/skills.md in sync")
                return 0
        except OSError:
            pass
        print("docs/skills.md is STALE - run build_skill_docs.py", file=sys.stderr)
        return 1
    out.write_text(text, encoding="utf-8")
    print("wrote %s" % out)
    return 0


if __name__ == "__main__":
    sys.exit(main())
